Katale/urls.py
__author__ = 'LT10'
from django.conf.urls import url, patterns
from . import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^signup/$', views.sign_up, name='signup'),
                       url(r'^login/$', views.user_login, name='login'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^account/$', views.account_details, name='account'),
                       url(r'^details/(?P<product_id>\w+)$', views.product_details, name='details'),
                       url(r'^products/(?P<category_id>\w+)$', views.products, name='products'),
                       url(r'^cart/$', views.show_cart, name='cart'),
                       url(r'^admin/$', views.admin, name='admin'),





)

Katale_Store/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import url, patterns
from Katale_Store import settings
from Katale import urls as Katale_urls


urlpatterns = [
    url(r'^Katale/', include(Katale_urls, namespace='Katale')),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static', (r'media/(?P<path>.*)',
                                'serve',
                                {'document_root': settings.MEDIA_ROOT})
    )

# THE IF LETS US CHECK IF THE PROJECT IS BEING RUN IN DEBUG MODE,I.E DEBUG IS TRUE

# THE NEW PATTERN
# ADDED MINS IF ANY FILE IS REQUESTED
# WITH A URL STATING WITH MEDIA/ THE REQUEST
# WILL B PASD TO THE DJANGO.VIEWS.STATIC VIEW

Katale/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Users(models.Model):
    user = models.OneToOneField(User)
    city = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    birthdate = models.DateField()
    phone_number = models.PositiveIntegerField(null=False, blank=False)

    class Meta:
        db_table = "Users"

    def __unicode__(self):
        return self.user.username


class Category(models.Model):
    category = models.CharField(max_length=50)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # parent = models.ForeignKey('self', blank=True, null=True, related_name='child')

    class Meta:
        db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Categories'

    def category_name(self):
        return self.category

    def __unicode__(self):
        return self.category


class SubCategory(models.Model):
    category = models.ForeignKey(Category, null=True, related_name='subcategories')
    sub_category_name = models.CharField(max_length=20)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'subcategories'

    def __unicode__(self):
        return self.sub_category_name


class Product(models.Model):
    product_name = models.CharField(max_length=30)
    description = models.TextField()
    price = models.PositiveIntegerField()
    image = models.ImageField(upload_to='images', max_length=50)
    category = models.ForeignKey(Category, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        db_table = 'Products'

    def __unicode__(self):
        return self.product_name


class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True, null=False)
    product = models.ForeignKey(Product, null=False, unique=False)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        db_table = 'Cart_Items'
        ordering = ['date_added']

    def total_price(self):
        return self.quantity * self.product.price

    def product_name(self):
        return self.product.product_name

    def price(self):
        return self.product.price

    def augment_quantity(self, quantity):
        self.quantity += int(quantity)
        self.save()

    def product_image(self):
        return self.product.image

Katale/forms.py
from django.forms.extras import SelectDateWidget

__author__ = 'LT10'

from django import forms
from django.core.exceptions import ValidationError
from .models import Users, Category, Product
from django.forms import ModelForm
from django.contrib.auth.models import User

BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')


class CategoryForm(ModelForm):
    category = forms.CharField(widget=forms.TextInput(attrs=dict(required=True)))
    description = forms.Textarea()

    class Meta:
        model = Category
        fields = ['category', 'description']


class ProductForm(ModelForm):
    image = forms.ImageField()

    class Meta:
        model = Product
        fields = "__all__"

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

    def __init__(self, data={}):
        super(UserForm, self).__init__(data=data)
        self.fields['password_again'] = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True)))

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        if cleaned_data.get('password') != cleaned_data.get('password_again'):
            raise ValidationError('Password Mismatch')
        else:
            return cleaned_data

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError('Username already taken, please choose another')


class UserRegistrationForm(ModelForm):
    city = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label="City")
    address = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label="Address")
    phone_number = forms.IntegerField(widget=forms.TextInput(attrs=dict(max_length=15, required=True)))
    birthdate = forms.DateField(widget=SelectDateWidget)

    class Meta:
        model = Users
        fields = ['city', 'address', 'phone_number', 'birthdate']


class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(
        widget=forms.TextInput(attrs={'size': '2', 'max_length': '5', 'value': '1', 'class': 'quantity'}),
        error_messages={'invalid': 'Please enter a valid quantity'}, min_value=1)
    product_id = forms.IntegerField(widget=forms.HiddenInput())

    # override the default __init__ so we can set the request
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(AddToCartForm, self).__init__(*args, **kwargs)

    # custom validation to check for cookies
    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError('Cookies must be enabled on your computer')
            return self.cleaned_data

Katale/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from .forms import UserRegistrationForm, UserForm, AddToCartForm, CategoryForm, ProductForm
from .models import Users, Category, Product
from Katale import cart


# Create your views here.


def index(request):
    category_list = Category.objects.order_by('created_at')
    # category_list = Category.objects.filter(parent__isnull=True)

    product_list = Product.objects.order_by('created_at')
    if request.method == 'POST':
        if request.user.is_authenticated():
            cart.add_to_cart(request)
        else:
            return render(request, 'Katale/login.html', {})
    cart_item_count = cart.cart_distinct_item_count(request)
    return render(request, 'Katale/index.html', {'categories': category_list, 'products': product_list,
                                                 'cart_count': cart_item_count})


def show_cart(request):
    category_list = Category.objects.order_by('created_at')
    if request.method == 'POST':
        postdata = request.POST.copy()
        if postdata['submit'] == 'Remove':
            cart.remove_from_cart(request)
        if postdata['submit'] == 'Update':
            cart.update_cart(request)
    cart_items = cart.get_cart_items(request)
    cart_item_count = cart.cart_distinct_item_count(request)
    cart_subtotal = cart.cart_total_price(request)
    # final_price = cart.cart_total_price(request)
    return render(request, 'Katale/cart.html',
                  {'products': cart_items, 'cart_count': cart_item_count, 'categories': category_list,
                   'sub_total': cart_subtotal})


def account_details(request):
    cart_item_count = cart.cart_distinct_item_count(request)

    return render(request, 'Katale/account.html', {'cart_count': cart_item_count})


def product_details(request, product_id):
    category_list = Category.objects.order_by('created_at')

    product = Product.objects.get(pk=product_id)

    if request.method == 'POST':
        if request.user.is_authenticated():
            postdata = request.POST.copy()
            form = AddToCartForm(request, postdata)
            if form.is_valid():
                cart.add_to_cart(request)
                # if test cookie worked, get rid of it
                if request.session.test_cookie_worked():
                    request.session.delete_test_cookie()


        else:
            return render(request, 'Katale/login.html', {})
    else:
        form = AddToCartForm()
        form.fields['product_id'].widget.attrs['value'] = product_id
        request.session.set_test_cookie()
    cart_item_count = cart.cart_distinct_item_count(request)
    return render(request, 'Katale/details.html', {'categories': category_list, 'product': product, 'cart_form': form,
                                                   'cart_count': cart_item_count, })


def products(request, category_id):
    category_list = Category.objects.order_by('created_at')

    product = Product.objects.filter(category_id=category_id)
    # product = Product.objects.filter(sub_category__category_id=category_id)

    if request.method == 'POST':
        if request.user.is_authenticated():
            cart.add_to_cart(request)
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
                # cart_items = cart.get_cart_items(request)
                # return render(request, 'Katale/cart.html', {'products': cart_items, 'cart_count': cart_item_count})
        else:
            return render(request, 'Katale/login.html', {})

    cart_item_count = cart.cart_distinct_item_count(request)
    return render(request, 'Katale/products.html', {'categories': category_list, 'products': product,
                                                    'cart_count': cart_item_count})


def sign_up(request):
    registered = False
    category_list = Category.objects.order_by('created_at')
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        user_profile = UserRegistrationForm(request.POST)
        if user_form.is_valid() and user_profile.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            userp = Users(user=user, city=user_profile.cleaned_data['city'],
                          address=user_profile.cleaned_data['address'],
                          birthdate=user_profile.cleaned_data['birthdate'],
                          phone_number=user_profile.cleaned_data['phone_number'])

            userp.save()
            registered = True
            registration_message = "You have been registered successfully"
            return render(request, 'Katale/login.html', {'user_form': user_form, 'user_profile': user_profile,
                                                         'categories': category_list, 'registered': registered,
                                                         'message': registration_message})

        else:
            form_errors = user_form.errors
            formm_errors = user_profile.errors
            return render(request, 'Katale/login.html',
                          {'errors': form_errors, 'error': formm_errors, 'user_form': user_form,
                           'user_profile': user_profile})

    else:
        user_form = UserForm()
        user_profile = UserRegistrationForm()
    return render(request, 'Katale/login.html',
                  {'user_form': user_form, 'user_profile': user_profile, 'categories': category_list})


def admin(request):
    category_list = Category.objects.order_by('created_at')
    product_list = Product.objects.all()
    category_form = CategoryForm()
    product_form = ProductForm()
    if request.user.is_authenticated():
        if request.method == 'POST':
            post_data = request.POST.copy()
            if post_data['submit'] == 'category':
                category_form = CategoryForm(request.POST)
                if category_form.is_valid():
                    category_form.save()
                    # message = 'Category added'
                    return render(request, 'Katale/admin.html', {})
                else:
                    error_form = category_form.errors
                    return render(request, 'Katale/admin.html', {'errors': error_form, 'category_form': category_form,
                                                                 'categories': category_list, 'products': product_list})
            if post_data['submit'] == 'product':
                product_form = ProductForm(request.POST, request.FILES)
                if product_form.is_valid():
                    product_form.save()
                    return render(request, 'Katale/login.html', {})
                else:
                    error_form = product_form.errors
                    return render(request, 'Katale/admin.html', {'errors': error_form, 'product_form': product_form,
                                                                 'categories': category_list, 'products': product_list})
            if post_data['submit'] == 'DeleteCategory':
                if request.method == 'POST':
                    categories_list = request.POST.getlist('categories')
                    for category in categories_list:
                        x = Category.objects.filter(category=category)
                        x.delete()
            if post_data['submit'] == 'DeleteProduct':
                product_id = post_data['product_id']
                product = Product.objects.filter(pk=product_id)
                product.delete()
            if post_data['submit'] == 'UpdateQuantity':
                product_id = post_data['product_id']
                quantity = int(post_data['quantity'])
                product = Product.objects.filter(pk=product_id)
                for x in product:
                    x.quantity = quantity
                    x.save()
            if post_data['submit'] == 'UpdatePrice':
                product_id = post_data['product_id']
                price = int(post_data['price'])
                product = Product.objects.filter(pk=product_id)
                for x in product:
                    x.price = price
                    x.save()
        else:
            return render(request, 'Katale/admin.html', {'category_form': category_form, 'product_form': product_form,
                                                         'categories': category_list, 'products': product_list})
    else:
        user_form = UserForm()
        user_profile = UserRegistrationForm()
        return render(request, 'Katale/login.html',
                      {'user_form': user_form, 'user_profile': user_profile, 'categories': category_list})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/Katale/')
        else:
            message = 'Invalid username or password.'
            return render(request, 'Katale/login.html', {'message': message})
    else:
        return render(request, 'Katale/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/Katale/')

Katale/templates/Katale/account.html
{% extends "Katale/base.html" %}
{% block title %}Katale | Account{% endblock title %}
{% block site_content %}
		<div class="container">
			<p>Account details</p>
				{% if user.is_authenticated %}
			<p>Username:{{ user.username}}</p>
			<p>First name:{{ user.first_name}}</p>
			<p>Last name:{{ user.last_name}}</p>
			<p>Email:{{ user.email}}</p>
			{% else %}
			<p>Please login or create an account</p>
			{% endif %}
		</div>
{% endblock %}

Katale/templates/Katale/details.html
{% extends "Katale/base.html" %}
{% load staticfiles %}
{% block title %}Katale | Product Details{% endblock title %}
{% block site_content %}
<section>
		<div class="container">
			<div class="row">
                <div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% if categories %}
							{% for category in categories%}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a href="{% url 'Katale:products' category.id %}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{category.category}}
										</a>
									</h4>
								</div>
							</div>
							{% endfor %}
							{% endif %}

						</div><!--/category-products-->
						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />
						</div>
                    </div>
                </div>

				<div class="col-sm-9 padding-right">

					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							{% if product %}


							<div class="view-product">
								<img src="{{product.image.url}}" alt="" />
							</div>


							<!--<div id="similar-product" class="carousel slide" data-ride="carousel">-->
								<!--{% if category_item %}-->
								<!--{% for product in category_item %}-->

								  <!--&lt;!&ndash; Wrapper for slides &ndash;&gt;-->
								    <!--<div class="carousel-inner">-->
										<!--<div>-->
										  <!--<a href=""><img src="{{product.image.url}}" alt="" width="85" height="84"></a>-->

										<!--</div>-->
									<!--</div>-->

								  <!--&lt;!&ndash; Controls &ndash;&gt;-->
								  <!--<a class="left item-control" href="#similar-product" data-slide="prev">-->
									<!--<i class="fa fa-angle-left"></i>-->
								  <!--</a>-->
								  <!--<a class="right item-control" href="#similar-product" data-slide="next">-->
									<!--<i class="fa fa-angle-right"></i>-->
								  <!--</a>-->
								<!--{% endfor %}-->
								<!--{% endif %}-->
							<!--</div>-->


						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!--<img src="images/product-details/new.jpg" class="newarrival" alt="" />-->
								<h2>{{product.product_name}}</h2>

								<!--<img src="images/product-details/rating.png" alt="" />-->
								<span>
									<span>Shs {{product.price}}</span>

								</span>
								<p><b>Description:</b>{{product.description}}</p>

                                 {% if product.quantity > 0 %}
								<p><b>Availability:</b> In Stock</p>
								{% else %}
								<p><b>Availability:</b>Out of Stock</p>
								{% endif %}
								<p><b>Condition:</b> New</p>
								<form method="post" action="{% url 'Katale:details' product.id %}" >

										{% csrf_token %}
										{{ cart_form.as_p}}

									<button type="submit" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
									</form>

								{% endif %}
							</div><!--/product-information-->

						</div>
					</div><!--/product-details-->


				</div>
			</div>
		</div>

    </section>


{% endblock %}

Katale/templates/Katale/index.html
{% extends "Katale/base.html" %}
{% load staticfiles %}
{% block title %}Katale | Home{% endblock title %}
{% block site_content %}
	
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						
						<div class="carousel-inner">
							<div class="item active">

								<div class="col-sm-6">

									<img src="{% static 'images/home/home_banner3.jpg' %}" alt="" width="990" height="441"/>

								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>KATALE</span></h1>
									<h2>Latest Collection</h2>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/girl2.jpg' %}" class="girl img-responsive" alt="" />
									</div>
							</div>
							
							<div class="item">
								<div class="col-sm-6">
									<h1><span>KATALE</span></h1>
									<h2>Big Discounts</h2>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/girl3.jpg' %}" class="girl img-responsive" alt="" />
									</div>
							</div>
							
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>
			</div>
		</div>
	</section><!--/slider-->
	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% if categories %}
							{% for category in categories%}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a href="{% url 'Katale:products' category.id %}" >
											<!--<span class="badge pull-right"><i class="fa fa-plus"></i></span>-->
											{{category.category}}
										</a>
									</h4>
								</div>

							</div>
							{% endfor %}
							{% endif %}

						</div><!--/category-products-->
						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/on3.jpg' %}" alt="" />
							<img src="{% static 'images/home/blank.png' %}" alt="" />
							<img src="{% static 'images/home/on1.jpg' %}" alt="" />
							<img src="{% static 'images/home/blank.png' %}" alt="" />
							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />
						</div>

					</div>
				</div>


				<div class="col-sm-9 padding-right">
					<div class="features_items" id='features_items'><!--features_items-->
						<h2 class="title text-center">Featured Items</h2>
						{% if products %}
						{% for product in products|slice:":9" %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<a href= "{% url 'Katale:details' product.id %}" />
											<img src="{{product.image.url}}" alt="" width="225" height="230" />
										    </a>
											<h2>UGX {{ product.price }}</h2>
										    <p>{{ product.product_name }}</p>
											<form method="post" action="." >
										        {% csrf_token %}
												<input type="hidden" name="product_id" value="{{ product.id }}" />
												<button type="submit" class="btn btn-fefault cart" value="Add">
													<i class="fa fa-shopping-cart"></i>
													Add to cart</button>
											</form>


										</div>

								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href= "{% url 'Katale:details' product.id %}" /> <i class="fa fa-plus-square"></i>Details</a></li>

									</ul>
								</div>
							</div>
						</div>
						{% endfor %}
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</section>

	{% endblock %}

Katale/templates/Katale/login.html
{% extends "Katale/base.html" %}
{% load staticfiles %}
{% block title %}Login | SignUp{% endblock title %}
{% block site_content %}

	
	<section id="form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h2>Login to your account</h2>
						<form action="{% url 'Katale:login' %}" method="post">
							{% csrf_token %}
							{% if message %}
							{{message}}
							{% endif%}
							<input type="text" placeholder="Username" name="username" />
							<input type="password" placeholder="Password"  name="password"/>

							<button type="submit" class="btn btn-default">Login</button>
						</form>
					</div><!--/login form-->
				</div>
				<div class="col-sm-1">
					<h2 class="or">OR</h2>
				</div>
				<div class="col-sm-4">
					<div class="signup-form"><!--sign up form-->
						{% if registered %}
						<script>
                           alert('{{ message }}');
                        </script>
						{% endif%}
						<h2>New User Signup!</h2>

						<form method="post" action="/Katale/signup/">
							{% csrf_token %}


							{{ user_form.as_p }}
							{{ user_profile.as_p }}

							<button type="submit" class="btn btn-default">Signup</button>
						</form>
					</div><!--/sign up form-->
				</div>
			</div>
		</div>
	</section><!--/form-->
	
	
{% endblock %}

Katale/templates/Katale/products.html
{% extends 'Katale/base.html' %}
{% load staticfiles %}
{% block title %}Katale|Products{% endblock title %}
{% block site_content %}

<section id="advertisement">
    <div class="container">
        <img src='{% static "images/home/Thailand-Shop-Online-Banner-2.gif" %}' alt="" height="146" />
    </div>
</section>
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        {% if categories %}
                        {% for category in categories%}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="{% url 'Katale:products' category.id %}" >
                                        {{category.category}}
                                    </a>
                                </h4>
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}

                    </div><!--/category-products-->
                    <div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />
						</div>
                </div>
            </div>


            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Features Items</h2>
                    {% if products %}
                    {% for product in products %}
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center">
                                    <a href= "{% url 'Katale:details' product.id %}" >

                                    <img width='225' height='230' src="{{product.image.url}}" alt="" />
                                    </a>

                                    <h2>UGX {{ product.price }}</h2>
                                    <p>{{ product.product_name }}</p>
                                    	<form method="post" action="{% url 'Katale:products' product.category.id %}">
										        {% csrf_token %}
												<input type="hidden" name="product_id" value="{{ product.id }}" />
												<button type="submit" class="btn btn-fefault cart" value="Add">
													<i class="fa fa-shopping-cart"></i>
													Add to cart</button>
											</form>

                                    <!--<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>-->
                                </div>

                            </div>
                            <div class="choose">
                                <ul class="nav nav-pills nav-justified">

                                    <li><a href="{% url 'Katale:details' product.id %}"><i class="fa fa-plus-square"></i>Details</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <!--<ul class="pagination">-->
                    <!--<li class="active"><a href="">1</a></li>-->
                    <!--<li><a href="">2</a></li>-->
                    <!--<li><a href="">3</a></li>-->
                    <!--<li><a href="">&raquo;</a></li>-->
                    <!--</ul>-->
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>

{% endblock %}